FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install sqlite3

EXPOSE 8080

#docker run -p 5000:5000 mlflow-server